language: node_js
node_js:
  - "8"
  
branches:
  only:
    - "master"
    
cache:
  directories:
    - "node_modules"
  yarn: true

before_script:
  - sudo apt-get -y install python3-pip python-dev
  - sudo pip3 install -U setuptools
  - sudo pip3 install -U virtualenvwrapper
  - python3 -V
  - pip3 -V
  - sudo pip3 install typing pyyaml
  - yarn global add elm elm-test elm-format

script: yarn test

deploy:
  provider: pages
  local-dir: public
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  on:
    branch: master
